import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createClient } from "@libsql/client";
import { applyPhase218Paili002Content } from "../../scripts/apply-phase218-paili-002-content";
import { PHASE218_PAILI_002_ID, PHASE218_PAILI_002_SLUG, PHASE218_PAILI_BRAND_ID } from "../../scripts/data/phase218-paili-002";
import { assertCatalogSnapshotUnchanged, copyCheckpointedCatalogToDisposableCopy, snapshotCatalogFiles } from "../../src/lib/audit/read-only-catalog";
import { migrateDatabase } from "../../src/lib/db";

const ROOT = process.cwd(); const REAL = path.join(ROOT, "data", "fpkg.db");
test("Phase 218 publishes Paili and Paili 002 on an owned copy", { timeout: 900_000 }, async () => {
  const snapshot = snapshotCatalogFiles(REAL); const ownedRoot = fs.mkdtempSync(path.join(os.tmpdir(), "fpkg-phase218-paili-")); const copy = copyCheckpointedCatalogToDisposableCopy(REAL, path.join(ownedRoot, "catalog.db"), ownedRoot, { expectedSourceSnapshot: snapshot }); const client = createClient({ url: `file:${copy.destinationPath}` }); const options = { workspaceRoot: ROOT, reviewer: "phase218-paili-002-test", databasePath: copy.destinationPath, ownedRoot, protectedCatalogPath: REAL, protectedCatalogSnapshot: snapshot, env: { ...process.env, TURSO_DATABASE_URL: "", TURSO_AUTH_TOKEN: "", FPKG_DATABASE_URL: "" } } as const;
  try { await migrateDatabase(client); await assert.rejects(() => applyPhase218Paili002Content(client, { ...options, env: { ...options.env, FPKG_DATABASE_URL: "libsql://remote" } }), /refuses inherited remote database selection/); const first = await applyPhase218Paili002Content(client, options); assert.deepEqual(first.entities.map((item) => item.entityId), [PHASE218_PAILI_BRAND_ID, PHASE218_PAILI_002_ID]); assert.ok(first.entities.every((item) => item.outcome === "published"), JSON.stringify(first)); const identities = await client.execute({ sql: "SELECT id,type,slug FROM entities WHERE id IN (?,?) ORDER BY id", args: [PHASE218_PAILI_BRAND_ID, PHASE218_PAILI_002_ID] }); assert.equal(identities.rows.length, 2); assert.equal(identities.rows.find((row) => row.id === PHASE218_PAILI_002_ID)?.slug, PHASE218_PAILI_002_SLUG); for (const entityId of [PHASE218_PAILI_BRAND_ID, PHASE218_PAILI_002_ID]) { const publicRow = await client.execute({ sql: "SELECT body_md,source FROM public_entities WHERE id=?", args: [entityId] }); const body = String(publicRow.rows[0]?.body_md ?? ""); assert.ok(Array.from(body).length >= (entityId === PHASE218_PAILI_002_ID ? 2000 : 1200)); assert.doesNotMatch(body, /canonical|made_by|retired|数据库|仓库/i); assert.match(String(publicRow.rows[0]?.source ?? ""), /curated-content:phase218/); assert.equal(Number((await client.execute({ sql: "SELECT count(*) AS value FROM media_assets WHERE entity_id=? AND usage_status='primary'", args: [entityId] })).rows[0]?.value), 1); } const modelBody = String((await client.execute({ sql: "SELECT body_md FROM public_entities WHERE id=?", args: [PHASE218_PAILI_002_ID] })).rows[0]?.body_md ?? ""); assert.match(modelBody, /透明|EF|converter|维护|选购/); assert.equal(Number((await client.execute({ sql: "SELECT count(*) AS value FROM entity_links WHERE source_id=? AND target_id=? AND link_type='made_by'", args: [PHASE218_PAILI_002_ID, PHASE218_PAILI_BRAND_ID] })).rows[0]?.value), 1); const replay = await applyPhase218Paili002Content(client, options); assert.ok(replay.entities.every((item) => item.outcome === "noop"), JSON.stringify(replay)); assertCatalogSnapshotUnchanged(snapshot); } finally { client.close(); fs.rmSync(ownedRoot, { recursive: true, force: true }); }
});
