-- Migration 010: Fix low-quality pen entity summaries
-- Criteria: summary < 20 chars, too generic (just brand name), or unhelpful placeholder

UPDATE entities SET summary = 'Admok出品入门级透明示范钢笔，可替换标准笔尖，性价比不错' WHERE id = 'oG3jXGONflH3';
UPDATE entities SET summary = '德国百年品牌Diplomat经典款太空梭，流线型笔身设计，不锈钢笔尖顺滑稳定' WHERE id = 'yWhmvp5a_J1A';
UPDATE entities SET summary = '美国老牌Esterbrook复兴后旗舰系列Estie加大版，复古与现代融合，握感舒适' WHERE id = 'Xn2g9NlYnU8t';
UPDATE entities SET summary = 'Kaweco AL Sport全铝合金口袋笔，CNC精加工笔身，便携且质感出众' WHERE id = 'MV78JwjMOd6h';
UPDATE entities SET summary = 'Kaweco Sport经典口袋笔，八角笔帽辨识度高，旋帽紧凑便携EDC首选' WHERE id = 'JhyxWW1Ylw-A';
UPDATE entities SET summary = 'Kaweco Student学生系列，经典造型配现代笔尖，Kaweco中端性价比之选' WHERE id = 'ZOuVvOu_nGSP';
UPDATE entities SET summary = '意大利手工品牌Leonardo旗舰Furore/Momento Magico，树脂笔身色彩层次丰富' WHERE id = 's0HAxT1gsHxh';
UPDATE entities SET summary = 'Noodler''s以防水墨水闻名，此为其配套钢笔，做工一般但适合调音实验' WHERE id = 'dLplUlM5weWq';
UPDATE entities SET summary = '台湾品牌SKB派顿出品，F10/F21系列定位入门级，品控稳定适合日常使用' WHERE id = '6K7UhGOj7VrS';
UPDATE entities SET summary = 'Tramol梵高系列以名画为灵感配色，艺术气息浓厚，B站有大量开箱评测' WHERE id = 'Yq-T86OfyarY';
UPDATE entities SET summary = '日本小众手工品牌Wancher Dream Pen系列，可选多种笔尖和上墨方式' WHERE id = '2aoD07lwSYCV';
UPDATE entities SET summary = '万宝龙144是停产经典款，14K金尖做工精良，二手市场是入手万宝龙金尖的平价方式' WHERE id = 'Eh5c49pldpwk';
UPDATE entities SET summary = '万宝龙艺术赞助人系列888限量版，纯金配件+漆艺笔身，顶级收藏品' WHERE id = 'AOnijUblJc72';
UPDATE entities SET summary = '万宝龙大文豪系列致敬文学巨匠，每款限量发行，收藏价值与工艺并重' WHERE id = 'C_eW3pcaf4yp';
UPDATE entities SET summary = '万宝龙学生龙22是停产入门金尖笔，二手市场是体验万宝龙14K金尖的最低门槛' WHERE id = 'nOIr_Up5WcyJ';
UPDATE entities SET summary = '万特佳Monteverde美国品牌，以多彩配色和性价比著称，Invincia系列为代表' WHERE id = 'ehhBLnGu6Uav';
UPDATE entities SET summary = '三文堂TWSBI Diamond Mini AL铝合金迷你版，便携活塞上墨，适合随身携带' WHERE id = '4fJHjzNt8KfK';
UPDATE entities SET summary = '三文堂TWSBI GO弹簧上墨款，最便宜的TWSBI入门选择，透明笔身可看墨水' WHERE id = 'LRlvQscC9w-i';
UPDATE entities SET summary = '上海97回归纪念款国产钢笔，具有时代纪念意义，怀旧收藏价值' WHERE id = 'A-m4SlNs1MJd';
UPDATE entities SET summary = '东吴DongWu 948国产老牌钢笔，定位平价日常书写工具' WHERE id = 'dbp20JATzwzm';
UPDATE entities SET summary = '中屋Nakaya Housoge高级定制莳绘笔，极少量纯手工制作，收藏级艺术品' WHERE id = 'XRyAh9ESgAP9';
UPDATE entities SET summary = '中屋Nakaya Portable Cigar是高端定制玩家的终极选择，14K金尖+定制漆艺笔身' WHERE id = 'yi6bQ5ulPD-W';
UPDATE entities SET summary = '中屋Nakaya Portable Writer黑溜涂，传统漆艺制作，极致匠心的书写工具' WHERE id = 'YeodugzY82yu';
UPDATE entities SET summary = '书乐ShuLe 2398国产平价钢笔，定位基础入门级书写工具' WHERE id = 'p81bNOu9URb7';
UPDATE entities SET summary = '依人YiRen 878国产品牌钢笔，定位平价日常书写' WHERE id = 'pJVODqR4jDGw';
UPDATE entities SET summary = '公爵Duke部分型号品控不稳，开箱翻车率较高，购买前建议看评测' WHERE id = '4lpmgqCxnJCs';
UPDATE entities SET summary = '写乐Sailor 1029银夹鱼雷中端型号，搭配冷色系墨水视觉更协调' WHERE id = 'Ga6QpPQiF0YT';
UPDATE entities SET summary = '写乐Sailor 1219标准鱼雷一航渠道约680元凑单可到539，性价比尚可' WHERE id = 'GXGa7rK83Jmi';
UPDATE entities SET summary = '写乐Sailor 1911/Profit系列是品牌核心产品线，覆盖多个价位段' WHERE id = 'mSvIKpw1GsoS';
UPDATE entities SET summary = '写乐Sailor Classic Ko经典系列，市场流通较少，笔尖调教细腻' WHERE id = 'MaxO_o9P4CXR';
UPDATE entities SET summary = '写乐Sailor Promenade漫步1031中端均衡之选，一航渠道475起适合日用' WHERE id = 'VyZ6lMsgEeUo';
UPDATE entities SET summary = '写乐Sailor转运石入门款，价格亲民是体验日系笔写感的最低门槛' WHERE id = '67U-NLL0isp6';
UPDATE entities SET summary = '凌美LAMY Logo低调日用款，不锈钢笔身设计简约，但性价比不如Safari' WHERE id = 'aHnnbObkUsOe';
UPDATE entities SET summary = '半句BanJu国产新锐设计品牌，注重笔身外观设计，适合追求个性的用户' WHERE id = 'QkevxuduEm9F';
UPDATE entities SET summary = '坛笔PenBBS 268旋帽示范笔，社区品牌有固定粉丝群，配色丰富' WHERE id = '6MSiaAQkLWEz';
UPDATE entities SET summary = '坛笔PenBBS 456活塞上墨款，大墨量适合重度书写，PenBBS经典产品' WHERE id = '4T9PI9yulxvA';
UPDATE entities SET summary = '坛笔PenBBS 469拉杆上墨入门款，PenBBS产品线中的特色型号' WHERE id = 'ZTVu5igxPOHe';
UPDATE entities SET summary = '坛笔PenBBS 494按动上墨款，PenBBS产品线中操作最便捷的型号' WHERE id = 'ndYHaLW2Ezp_';
UPDATE entities SET summary = '坛笔PenBBS金尖大明尖，PenBBS金尖产品线代表，社区口碑不错' WHERE id = 'NDr2-AGIGThf';
UPDATE entities SET summary = '塞尔Saier 3.0 EF尖国产入门笔，极细笔尖适合小字书写和手帐' WHERE id = 'q3zuCzJLQmZl';
UPDATE entities SET summary = '大公Dagong 56揿动式国产按动钢笔，按动机制方便快捷价格亲民' WHERE id = 'A8H1NwxfcPhT';
UPDATE entities SET summary = '意大利百年品牌Aurora奥罗拉，Optima系列以独特树脂笔身和自家金尖著称' WHERE id = 'G9ptvLpfyzNQ';
UPDATE entities SET summary = '威迪文Waterman权威Expert中端系列，商务风格设计品质稳定' WHERE id = 'YAiCRah1XAsz';
UPDATE entities SET summary = '威迪文Waterman查尔斯顿Hemisphere入门系列，优雅造型适合办公场景' WHERE id = 'gwKClNnwt3V3';
UPDATE entities SET summary = '并木Namiki Emperor帝王级莳绘笔，极高端收藏品纯手工制作全球限量' WHERE id = 'VZS9MQ7WtHev';
UPDATE entities SET summary = '并木Namiki Yukari Royale皇家缘，18K金尖+传统莳绘工艺极为精美' WHERE id = 'RzscQ2aowvn4';
UPDATE entities SET summary = '并木Namiki飞升龙莳绘笔，Reddit钢笔社区热门收藏讨论对象' WHERE id = 'rf4xDTwosdya';
UPDATE entities SET summary = '弘典HongDian 1866中端产品，金属笔身做工扎实书写顺滑' WHERE id = '1cA0oEMF7d1u';
UPDATE entities SET summary = '弘典HongDian 516低价入门款，价格低廉品质尚可适合初学者' WHERE id = 'BbfCEIAkG7C_';
UPDATE entities SET summary = '弘典HongDian 517/517s入门款，不锈钢尖书写稳定性价比高' WHERE id = '3Rkby4EUNPt0';
UPDATE entities SET summary = '弘典HongDian 6013文武黑将中端款，金属笔身设计有质感' WHERE id = 'bTFoxeal7c7T';
UPDATE entities SET summary = '弘典HongDian 620鸡尾酒颜值设计款，配色独特适合追求个性的用户' WHERE id = 'WUzZY3Y3y7-1';
UPDATE entities SET summary = '弘典HongDian M2迷你款便携入门笔，小巧可爱适合随身携带' WHERE id = 'CCUWJJaN7snC';
UPDATE entities SET summary = '弘典HongDian秦低价入门款，中国风设计元素价格亲民' WHERE id = 'F9Fb7joURlNH';
UPDATE entities SET summary = '弘典HongDian远航者系列，定位中端日常书写工具' WHERE id = '_tLM8vJHVGyr';
UPDATE entities SET summary = '弘典HongDian黑森林/黑森林Pro(1861)经典款，全黑设计辨识度高口碑稳定' WHERE id = 'GOTYyfNxvLAE';
UPDATE entities SET summary = '得力克Delike元素系列国产小众钢笔，独特外观设计价格亲民' WHERE id = '_gbRalCJARx3';
UPDATE entities SET summary = '意斯华P36国产笔常被拿来和末匠V60对比各有优劣适合喜欢对比选购' WHERE id = 'cVCGtVIb8WBd';
UPDATE entities SET summary = '文采KACO Edge刀锋系列，超薄笔身设计感突出适合商务场景' WHERE id = 'mB3Ad49lhus2';
UPDATE entities SET summary = '德国品牌施耐德Schneider BK402平价入门笔，品控稳定适合学生日常' WHERE id = 'MilfdAoWAAJz';
UPDATE entities SET summary = '末匠Majohn 80mini-E迷你款便携钢笔，小巧机身适合随身EDC' WHERE id = '2wR-Ix08dC-F';
UPDATE entities SET summary = '末匠Majohn F9法师独特外观设计，末匠产品线中的个性化选择' WHERE id = 'jzMyPAQvAzeF';
UPDATE entities SET summary = '末匠Majohn M2透明示范笔，可观察墨水余量价格亲民' WHERE id = 'f1DaQYtCJVMk';
UPDATE entities SET summary = '末匠Majohn P140定位中端日常书写，末匠产品线中的稳定选择' WHERE id = 'GxLe3PSmZALi';
UPDATE entities SET summary = '末匠Majohn Q1入门款迷你钢笔，价格低廉适合初次尝试' WHERE id = 'FGW7K6dv4Dry';
UPDATE entities SET summary = '末匠Majohn V1负压上墨透明示范笔，169块体验负压上墨+可视墨量' WHERE id = '9Tb_A-lzzLOi';
UPDATE entities SET summary = '末匠Majohn丸彩迷你便携笔，揣兜里或化妆包不占地方适合EDC' WHERE id = 'OKxZn-scQfN5';
UPDATE entities SET summary = '欧领Campus校园系列国产品牌，品控稳定出水顺畅不给惊吓' WHERE id = '6nwjVw9OWbpw';
UPDATE entities SET summary = '毕加索Picasso 916国产经典入门笔，明尖设计价格亲民' WHERE id = 'FZaeo2DF5_Qd';
UPDATE entities SET summary = '永生WingSung 3013仅24块体验负压上墨乐趣，性价比极高的入门选择' WHERE id = 'bV6wU3C9NxNi';
UPDATE entities SET summary = '永生WingSung 322基础入门款，价格低廉适合学生日常使用' WHERE id = 'sahAk7o8xVkj';
UPDATE entities SET summary = '永生WingSung 601A是601衍生型号，小幅改进笔尖和笔身设计' WHERE id = 'JyzeY3oQZxT4';
UPDATE entities SET summary = '永生WingSung 618活塞上墨款，大墨量适合重度书写用户' WHERE id = 'u7s4ejpej4hj';
UPDATE entities SET summary = '永生WingSung 699负压上墨款，密封性好性价比不错' WHERE id = 'b5VFRaOVWE7C';
UPDATE entities SET summary = '永生WingSung 729可DIY拆解设计，动手党会觉得有趣怕麻烦选金豪' WHERE id = 'lMq83WGl2qss';
UPDATE entities SET summary = '永生WingSung 840基础款日常书写工具，价格低廉品质尚可' WHERE id = 'GQPZwNqA_iVT';
UPDATE entities SET summary = '永续YongXu国产品牌，主打低价入门级钢笔市场' WHERE id = '01F-xAGy6sDr';
UPDATE entities SET summary = '派克Parker 51经典/Vintage版，暗尖设计书写顺滑，钢笔史上标志性产品' WHERE id = 'i_XH37icAI5C';
UPDATE entities SET summary = '派克Parker乔特Jotter最便宜的入门款，圆珠笔同款笔身价格亲民' WHERE id = 'lmNEK_3PuF_t';
UPDATE entities SET summary = '派克Parker威雅Vector，150以下能买到的进口品牌但整体定位偏低' WHERE id = 'ZxZjOj45mkq4';
UPDATE entities SET summary = '派利Paili 002国产入门级钢笔，价格低廉适合学生日常书写' WHERE id = 'ZmHH94j5tJQo';
UPDATE entities SET summary = '烂笔头Lanbitou 3059国产超低价钢笔，极致性价比适合大量练字' WHERE id = 'v_9J04P6xdfo';
UPDATE entities SET summary = '犀飞利Sheaffer帝国元首高端系列，代表美系老牌工艺水平' WHERE id = '5JqrNzxFsWC6';
UPDATE entities SET summary = '犀飞利Sheaffer美国老牌钢笔，以触碰上墨和Snorkel潜艇机构闻名' WHERE id = '_ELHatoNATQ4';
UPDATE entities SET summary = '白金Platinum富士旬景PNB-13000是3776升级版，树脂笔身更精致' WHERE id = 'ogo1UmxmcXJT';
UPDATE entities SET summary = '白金Platinum小流星PQ200最入门款，价格友好适合初体验白金品质' WHERE id = 'Er9lACPas9qm';
UPDATE entities SET summary = '白金Platinum总统President高端产品，18K金尖做工精湛是白金旗舰' WHERE id = 'a1t4DNomp4Ge';
UPDATE entities SET summary = '白金Platinum莳绘系列收藏级传统工艺，日本莳绘技法精美绝伦' WHERE id = '7dEIl-3axPwa';
UPDATE entities SET summary = '白雪Snowhite FP20文具品牌跨界钢笔产品，价格低廉定位基础书写' WHERE id = 'ex6eI7i__J5s';
UPDATE entities SET summary = '百乐Pilot 88G与78G+同系产品，知名度稍低但同样好写价格更亲民' WHERE id = '2GM0UtshoSVw';
UPDATE entities SET summary = '百乐Pilot 912 PO尖特殊笔尖型号，适合特定书写需求Reddit讨论较多' WHERE id = '1Dcfc2GsaaV4';
UPDATE entities SET summary = '百乐Pilot Cavalier细杆设计适合EDC随身，金属笔身质感好便携性强' WHERE id = 'BM2fNJ2-fP0T';
UPDATE entities SET summary = '百乐Pilot Prera日本本土热销款，体积小巧配色丰富适合手帐使用' WHERE id = 'UrbBB-onjGnF';
UPDATE entities SET summary = '百乐Pilot笑脸Kakuno入门练字推荐，可爱笑脸笔夹儿童学生首选' WHERE id = 'U6w1BK0N4u0f';
UPDATE entities SET summary = '百乐Pilot贵妃Cocoon定位轻商务，外观体面适合送礼或办公使用' WHERE id = '1dtEi80xLCZ1';
UPDATE entities SET summary = '百利金Pelikan M1000旗舰最大尺寸，除非手特别大否则M800更均衡' WHERE id = '6eXuisf9KiK5';
UPDATE entities SET summary = '百利金Pelikan M1005 Stresemann限量灰条纹配色，极为稀有收藏价值高' WHERE id = 'U1FyHpt9jaE4';
UPDATE entities SET summary = '百利金Pelikan M200入门款，树脂笔身活塞上墨性价比不错的德系选择' WHERE id = 'uLrDh27Q5Xne';
UPDATE entities SET summary = '百利金Pelikan M605白乌龟圈内人气很高，白条纹配色辨识度极佳' WHERE id = 'hO_QkEZd8uyh';
UPDATE entities SET summary = '百利金Pelikan M815是M800特殊配色变体，限量生产收藏价值较高' WHERE id = '2muSiS2rOSd7';
UPDATE entities SET summary = '百利金Pelikan P457入门级常被拿来和Safari对比，性价比各有千秋' WHERE id = 'wnzMt5lugvtc';
UPDATE entities SET summary = '维斯康蒂Visconti Rembrandt伦勃朗入门款，磁性笔帽设计独特性价比不错' WHERE id = 'V-pqNGhhGDZb';
UPDATE entities SET summary = '维斯康蒂Visconti Van Gogh梵高系列，以名画为灵感配色每支独一无二' WHERE id = 'eL1U08XLB3lS';
UPDATE entities SET summary = '犀飞利Sheaffer 329品控近年有改善，价格低廉适合入门体验老牌品质' WHERE id = 'skqRmcjdowQg';
UPDATE entities SET summary = '英雄派迪Hero Paddy一体尖国产特色笔，一体尖设计适合喜欢特殊笔尖体验' WHERE id = 'eDbt5freEPtb';
UPDATE entities SET summary = '辉柏嘉Faber-Castell Ambition雄心中端系列，设计感强多种材质笔杆可选' WHERE id = 'FBaxbvx7xTbo';
UPDATE entities SET summary = '辉柏嘉Faber-Castell E-Motion尚品注重笔身材质，独特造型适合追求质感' WHERE id = 'HhQgvkpTJhEc';
UPDATE entities SET summary = '逗万DouWan流光系列国产新锐品牌，颜值设计在线适合追求个性的年轻用户' WHERE id = 'jOcjUk_JB-XK';
UPDATE entities SET summary = '金星JinXing双尖钢笔国产特色，正反两面可书写适合喜欢特殊书写体验' WHERE id = 'RWv0fTpEcwuL';
UPDATE entities SET summary = '金豪Jinhao 10号50价位惊喜产品，做工超出价位预期性价比极高' WHERE id = 'ybN-vyW4nRbM';
UPDATE entities SET summary = '金豪Jinhao 313超低价入门产品，极致性价比适合学生党批量购入' WHERE id = 'gAxOYWXf25TY';
UPDATE entities SET summary = '金豪Jinhao 619班级团购神器，1688批发约3元一支极致性价比' WHERE id = 'LpJabRAW_0Pu';
UPDATE entities SET summary = '金豪Jinhao 75入门级产品，价格低廉品质尚可适合初次尝试' WHERE id = 'U8RkDxnXNxqo';
UPDATE entities SET summary = '金豪Jinhao 80细尖款，适合写小字和精细书写场景' WHERE id = 'V3GOJ5Q1Ra9-';
UPDATE entities SET summary = '金豪Jinhao 85暗尖设计，类似派克51的低调书写风格价格亲民' WHERE id = 'dnrQK31VKUst';
UPDATE entities SET summary = '金豪Jinhao 86产品线中的平价选择，适合日常基础书写' WHERE id = 'QDTizFrfcTbS';
UPDATE entities SET summary = '金豪Jinhao 9035产品线中的平价选择，适合日常基础书写' WHERE id = 'Y5hFEra6hHop';
UPDATE entities SET summary = '金豪Jinhao 911经典款口碑稳定，长期畅销适合日常使用' WHERE id = 'CVSvZoIPB42k';
UPDATE entities SET summary = '金豪Jinhao X159/159海外爆款，圈内讨论热度高性价比突出' WHERE id = 'mP8BPi8qUHSI';
UPDATE entities SET summary = '金豪Jinhao纯银镂空世纪不到100块，有银饰元素的高性价比钢笔' WHERE id = 'vspGwjDxROQ-';
UPDATE entities SET summary = '铃兰Lily 910国产按动钢笔，按动机制方便快捷价格亲民' WHERE id = 'dinM62TunTr8';
UPDATE entities SET summary = '长江ZhangJiang 988国产品牌平价钢笔，定位基础日常书写' WHERE id = 'fTRyXVmvdg58';
UPDATE entities SET summary = '高仕Cross莎士比亚130-180价位，国际品牌最低门槛做工比国产精细' WHERE id = 'NjUsoC-HoMM_';

-- Total: 123 summaries updated