import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import type { Client } from "@libsql/client";
import { assertCatalogSnapshotUnchanged, snapshotCatalogFiles } from "../src/lib/audit/read-only-catalog";
import { applyCuratedContentPacks, type ApplyPhase22Options, type ApplyPhase22Result } from "./apply-phase22-content";
import { PHASE97_ADMOK_BRAND_ID, PHASE97_ADMOK_J800_ID, phase97AdmokJ800Packs } from "./data/phase97-admok-j800";

export type ApplyPhase97Options = ApplyPhase22Options;
export type ApplyPhase97Result = ApplyPhase22Result;
const id = (prefix: string, value: string) => `${prefix}-${createHash("sha256").update(value).digest("hex").slice(0, 24)}`;
const inside = (candidate: string, root: string) => { const relative = path.relative(root, candidate); return relative !== "" && !relative.startsWith("..") && !path.isAbsolute(relative); };
async function owned(client: Client, options: ApplyPhase97Options) { for (const key of ["TURSO_DATABASE_URL", "TURSO_AUTH_TOKEN", "FPKG_DATABASE_URL"] as const) if ((options.env ?? process.env)[key]?.trim()) throw new Error(`Phase 97 refuses inherited remote selection: ${key}.`); assertCatalogSnapshotUnchanged(options.protectedCatalogSnapshot); const root = fs.realpathSync.native(options.ownedRoot), database = fs.realpathSync.native(options.databasePath), protectedCatalog = fs.realpathSync.native(options.protectedCatalogPath); if (!fs.statSync(root).isDirectory() || !fs.statSync(database).isFile() || fs.lstatSync(options.databasePath).isSymbolicLink() || !inside(database, root)) throw new Error("Phase 97 database must be a non-symlink file inside the owned root."); const own = fs.statSync(database, { bigint: true }), real = fs.statSync(protectedCatalog, { bigint: true }); if (database === protectedCatalog || (own.dev === real.dev && own.ino === real.ino)) throw new Error("Phase 97 refuses protected catalog or hard-link alias."); const listed = await client.execute("PRAGMA database_list"), main = listed.rows.find((row) => String(row.name) === "main"); if (!main?.file || fs.realpathSync.native(String(main.file)) !== database) throw new Error("Phase 97 client is not bound to the authorized owned copy."); const migration = await client.execute({ sql: "SELECT 1 FROM migrations WHERE name=? AND checksum IS NOT NULL", args: ["032_taxonomy_identity.sql"] }); if (migration.rows.length !== 1) throw new Error("Phase 97 owned copy must be migrated through 032."); }
async function topology(client: Client) { const transaction = await client.transaction("write"); try { const brand = await transaction.execute({ sql: "SELECT type,slug FROM entities WHERE id=?", args: [PHASE97_ADMOK_BRAND_ID] }), pen = await transaction.execute({ sql: "SELECT type,slug FROM entities WHERE id=?", args: [PHASE97_ADMOK_J800_ID] }); if (brand.rows.length !== 1 || String(brand.rows[0]?.type) !== "brand" || String(brand.rows[0]?.slug) !== "admok") throw new Error("Phase 97 Admok brand identity mismatch."); if (pen.rows.length !== 1 || String(pen.rows[0]?.type) !== "pen" || String(pen.rows[0]?.slug) !== "admok-简800") throw new Error("Phase 97 J800 identity mismatch."); await transaction.execute({ sql: "UPDATE entities SET name=? WHERE id=?", args: ["Admok J800（简800）", PHASE97_ADMOK_J800_ID] }); await transaction.execute({ sql: "DELETE FROM entity_links WHERE source_id=? AND link_type='made_by' AND target_id<>?", args: [PHASE97_ADMOK_J800_ID, PHASE97_ADMOK_BRAND_ID] }); await transaction.execute({ sql: "INSERT OR IGNORE INTO entity_links (id,source_id,target_id,link_type,reason) VALUES (?,?,?,'made_by',?)", args: [id("phase97-made-by", PHASE97_ADMOK_J800_ID), PHASE97_ADMOK_J800_ID, PHASE97_ADMOK_BRAND_ID, "Phase 97 exact Admok J800 maker relation"] }); await transaction.execute({ sql: "INSERT OR IGNORE INTO entity_links (id,source_id,target_id,link_type,reason) VALUES (?,?,?,'reverse',?)", args: [id("phase97-reverse", PHASE97_ADMOK_J800_ID), PHASE97_ADMOK_BRAND_ID, PHASE97_ADMOK_J800_ID, "Phase 97 Admok brand-to-model navigation"] }); await transaction.commit(); } catch (error) { if (!transaction.closed) await transaction.rollback(); throw error; } }
export async function applyPhase97AdmokJ800Content(client: Client, options: ApplyPhase97Options): Promise<ApplyPhase97Result> { await owned(client, options); await topology(client); const result = await applyCuratedContentPacks(client, options, structuredClone(phase97AdmokJ800Packs)); assertCatalogSnapshotUnchanged(options.protectedCatalogSnapshot); return result; }
const value = (name: string) => { const index = process.argv.indexOf(name); return index === -1 ? null : process.argv[index + 1] ?? null; };
async function main() { const databasePath = value("--database"), ownedRoot = value("--owned-root"), protectedCatalogPath = value("--protected-catalog"); if (!databasePath || !ownedRoot || !protectedCatalogPath) throw new Error("Usage: tsx scripts/apply-phase97-admok-j800-content.ts --database <owned-copy> --owned-root <root> --protected-catalog <real-db>"); const { createClient } = await import("@libsql/client"); const client = createClient({ url: `file:${path.resolve(databasePath)}` }); try { process.stdout.write(`${JSON.stringify(await applyPhase97AdmokJ800Content(client, { workspaceRoot: process.cwd(), reviewer: value("--reviewer") ?? "phase97-admok-j800", databasePath: path.resolve(databasePath), ownedRoot: path.resolve(ownedRoot), protectedCatalogPath: path.resolve(protectedCatalogPath), protectedCatalogSnapshot: snapshotCatalogFiles(path.resolve(protectedCatalogPath)), env: { ...process.env, TURSO_DATABASE_URL: "", TURSO_AUTH_TOKEN: "", FPKG_DATABASE_URL: "" } }), null, 2)}\n`); } finally { client.close(); } }
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) void main().catch((error) => { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
