import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { createClient, type Client, type Transaction } from "@libsql/client";
import { assertCatalogSnapshotUnchanged, snapshotCatalogFiles } from "../src/lib/audit/read-only-catalog";
import { applyCuratedContentPacks, type ApplyPhase22Options, type ApplyPhase22Result } from "./apply-phase22-content";
import { loadCuratedEntityPack } from "./lib/curated-content-pack";
import { PHASE158_PENBBS_456_ID, PHASE158_PENBBS_456_OLD_SLUG, PHASE158_PENBBS_456_SLUG, PHASE158_PENBBS_BRAND_ID, phase158PenBbs456Packs } from "./data/phase158-penbbs-456";

export type ApplyPhase158Options = ApplyPhase22Options;
export type ApplyPhase158Result = ApplyPhase22Result;
function stableId(prefix: string, value: string): string { return `${prefix}-${createHash("sha256").update(value).digest("hex").slice(0, 24)}`; }
function inside(candidate: string, root: string): boolean { const relative = path.relative(root, candidate); return relative !== "" && !relative.startsWith("..") && !path.isAbsolute(relative); }
function noRemote(options: ApplyPhase158Options): void { for (const key of ["TURSO_DATABASE_URL", "TURSO_AUTH_TOKEN", "FPKG_DATABASE_URL"] as const) if (options.env?.[key]?.trim()) throw new Error(`Phase 158 refuses inherited remote database selection: ${key}.`); }
async function authority(client: Client, options: ApplyPhase158Options): Promise<void> { noRemote(options); assertCatalogSnapshotUnchanged(options.protectedCatalogSnapshot); const root = fs.realpathSync.native(options.ownedRoot); const database = fs.realpathSync.native(options.databasePath); const protectedPath = fs.realpathSync.native(options.protectedCatalogPath); if (!fs.statSync(root).isDirectory() || !fs.statSync(database).isFile() || fs.lstatSync(options.databasePath).isSymbolicLink() || !inside(database, root)) throw new Error("Phase 158 requires an owned, non-symlink catalog copy."); const own = fs.statSync(database, { bigint: true }); const real = fs.statSync(protectedPath, { bigint: true }); if (database === protectedPath || (own.dev === real.dev && own.ino === real.ino)) throw new Error("Phase 158 refuses the protected catalog or hard-link alias."); const listed = await client.execute("PRAGMA database_list"); const main = listed.rows.find((row) => String(row.name) === "main"); if (!main?.file || fs.realpathSync.native(String(main.file)) !== database) throw new Error("Phase 158 client is not bound to the authorized owned copy."); const migration = await client.execute({ sql: "SELECT 1 FROM migrations WHERE name=? AND checksum IS NOT NULL", args: ["032_taxonomy_identity.sql"] }); if (migration.rows.length !== 1) throw new Error("Phase 158 owned copy must be migrated through 032."); }
async function ensureIdentity(client: Client): Promise<void> { const tx = await client.transaction("write"); try { const brand = await tx.execute({ sql: "SELECT type,slug FROM entities WHERE id=?", args: [PHASE158_PENBBS_BRAND_ID] }); if (brand.rows.length !== 1 || String(brand.rows[0]?.type) !== "brand" || String(brand.rows[0]?.slug) !== "penbbs") throw new Error("Phase 158 PenBBS brand identity mismatch."); const old = await tx.execute({ sql: "SELECT type,slug FROM entities WHERE id=?", args: [PHASE158_PENBBS_456_ID] }); if (old.rows.length !== 1 || String(old.rows[0]?.type) !== "pen" || String(old.rows[0]?.slug) !== PHASE158_PENBBS_456_OLD_SLUG) throw new Error(`Phase 158 expected existing PenBBS 456 at ${PHASE158_PENBBS_456_OLD_SLUG}.`); const collision = await tx.execute({ sql: "SELECT id FROM entities WHERE slug=? AND id<>?", args: [PHASE158_PENBBS_456_SLUG, PHASE158_PENBBS_456_ID] }); if (collision.rows.length !== 0) throw new Error("Phase 158 PenBBS 456 canonical slug collision."); await tx.execute({ sql: "UPDATE entities SET slug=?, name=? WHERE id=?", args: [PHASE158_PENBBS_456_SLUG, "PenBBS 456", PHASE158_PENBBS_456_ID] }); const batchKey = "phase158-penbbs-456-canonical"; const batchId = stableId("phase158-batch", batchKey); const actionId = stableId("phase158-action", batchKey); await tx.execute({ sql: "INSERT OR IGNORE INTO taxonomy_batches (id,source_key,source_checksum,status,note) VALUES (?,?,?,'applied',?)", args: [batchId, batchKey, createHash("sha256").update(batchKey).digest("hex"), "Canonicalize existing PenBBS 456 route."] }); await tx.execute({ sql: "INSERT OR IGNORE INTO taxonomy_actions (id,batch_id,source_row_key,action_kind,action_checksum,source_entity_id,target_entity_id,status,note) VALUES (?,?,?,'rename',? ,?,?, 'applied',?)", args: [actionId, batchId, batchKey, createHash("sha256").update(`${batchKey}:rename`).digest("hex"), PHASE158_PENBBS_456_ID, PHASE158_PENBBS_456_ID, "Use /pen/penbbs-456 as the unambiguous PenBBS 456 route."] }); const redirect = await tx.execute({ sql: "SELECT redirect_kind,target_path FROM entity_redirects WHERE source_path=?", args: [`/pen/${PHASE158_PENBBS_456_OLD_SLUG}`] }); if (redirect.rows.length === 0) await tx.execute({ sql: "INSERT INTO entity_redirects (id,batch_id,action_id,source_path,target_path,redirect_kind,fallback_reason) VALUES (?,?,?,?,?,'permanent',?)", args: [stableId("phase158-redirect", PHASE158_PENBBS_456_OLD_SLUG), batchId, actionId, `/pen/${PHASE158_PENBBS_456_OLD_SLUG}`, `/pen/${PHASE158_PENBBS_456_SLUG}`, "canonical_model_route"] }); else if (String(redirect.rows[0]?.redirect_kind) !== "permanent" || String(redirect.rows[0]?.target_path) !== `/pen/${PHASE158_PENBBS_456_SLUG}`) throw new Error("Phase 158 conflicting PenBBS 456 redirect."); await tx.commit(); } catch (error) { if (!tx.closed) await tx.rollback(); throw error; } }
async function ensureIdentityIfNeeded(client: Client): Promise<void> { const row = await client.execute({ sql: "SELECT type,slug FROM entities WHERE id=?", args: [PHASE158_PENBBS_456_ID] }); if (row.rows.length !== 1 || String(row.rows[0]?.type) !== "pen") throw new Error("Phase 158 PenBBS 456 entity is missing or has the wrong type."); const slug = String(row.rows[0]?.slug); if (slug === PHASE158_PENBBS_456_OLD_SLUG) { await ensureIdentity(client); return; } if (slug !== PHASE158_PENBBS_456_SLUG) throw new Error(`Phase 158 unexpected PenBBS 456 slug: ${slug}`); }
async function topology(client: Client): Promise<void> { const tx: Transaction = await client.transaction("write"); try { const pen = await tx.execute({ sql: "SELECT type,slug FROM entities WHERE id=?", args: [PHASE158_PENBBS_456_ID] }); if (pen.rows.length !== 1 || String(pen.rows[0]?.type) !== "pen" || String(pen.rows[0]?.slug) !== PHASE158_PENBBS_456_SLUG) throw new Error("Phase 158 PenBBS 456 canonical identity mismatch after rename."); await tx.execute({ sql: "DELETE FROM entity_links WHERE source_id=? AND link_type='made_by' AND target_id<>?", args: [PHASE158_PENBBS_456_ID, PHASE158_PENBBS_BRAND_ID] }); await tx.execute({ sql: "INSERT OR IGNORE INTO entity_links(id,source_id,target_id,link_type,reason) VALUES(?,?,?,'made_by',?)", args: [stableId("phase158-made-by", PHASE158_PENBBS_456_ID), PHASE158_PENBBS_456_ID, PHASE158_PENBBS_BRAND_ID, "Phase 158 verified PenBBS 456 maker relation"] }); await tx.execute({ sql: "DELETE FROM entity_links WHERE source_id=? AND target_id=? AND link_type='reverse' AND id<>?", args: [PHASE158_PENBBS_BRAND_ID, PHASE158_PENBBS_456_ID, stableId("phase158-reverse", PHASE158_PENBBS_456_ID)] }); await tx.execute({ sql: "INSERT OR IGNORE INTO entity_links(id,source_id,target_id,link_type,reason) VALUES(?,?,?,'reverse',?)", args: [stableId("phase158-reverse", PHASE158_PENBBS_456_ID), PHASE158_PENBBS_BRAND_ID, PHASE158_PENBBS_456_ID, "Phase 158 PenBBS brand-to-456 navigation"] }); await tx.commit(); } catch (error) { if (!tx.closed) await tx.rollback(); throw error; } }
export async function applyPhase158PenBbs456Content(client: Client, options: ApplyPhase158Options): Promise<ApplyPhase158Result> { await authority(client, options); await ensureIdentityIfNeeded(client); await topology(client); const packs = phase158PenBbs456Packs.map((pack) => loadCuratedEntityPack(fs.realpathSync.native(options.workspaceRoot), pack)); const result = await applyCuratedContentPacks(client, options, packs); assertCatalogSnapshotUnchanged(options.protectedCatalogSnapshot); return result; }
function value(name: string): string | null { const index = process.argv.indexOf(name); return index === -1 ? null : process.argv[index + 1] ?? null; }
async function main(): Promise<void> { const database = value("--database"); const ownedRoot = value("--owned-root"); const protectedCatalog = value("--protected-catalog"); if (!database || !ownedRoot || !protectedCatalog) throw new Error("Usage: tsx scripts/apply-phase158-penbbs-456-content.ts --database <owned-copy> --owned-root <root> --protected-catalog <real-db> [--reviewer <name>]"); const resolvedDatabase = path.resolve(database); const resolvedProtected = path.resolve(protectedCatalog); const client = createClient({ url: `file:${resolvedDatabase}` }); try { const result = await applyPhase158PenBbs456Content(client, { workspaceRoot: process.cwd(), reviewer: value("--reviewer") ?? "phase158-penbbs-456", databasePath: resolvedDatabase, ownedRoot: path.resolve(ownedRoot), protectedCatalogPath: resolvedProtected, protectedCatalogSnapshot: snapshotCatalogFiles(resolvedProtected), env: { ...process.env, TURSO_DATABASE_URL: "", TURSO_AUTH_TOKEN: "", FPKG_DATABASE_URL: "" } }); process.stdout.write(`${JSON.stringify(result, null, 2)}\n`); } finally { client.close(); } }
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) void main().catch((error) => { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
