import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import type { Client } from "@libsql/client";
import { assertCatalogSnapshotUnchanged } from "../src/lib/audit/read-only-catalog";
import { applyCuratedContentPacks, type ApplyPhase22Options, type ApplyPhase22Result } from "./apply-phase22-content";
import { PHASE49_CRYSTAL_DREAM_ID, PHASE49_DARK_CRYSTAL_ID, PHASE49_LAVA_BRONZE_ID, PHASE49_LAVA_COLOR_ID, PHASE49_LAVA_DARK_AGE_ID, PHASE49_VISCONTI_BRAND_ID, PHASE49_VISCONTI_OLD_HOMO_ID, phase49ViscontiHomoSapiensPacks } from "./data/phase49-visconti-homo-sapiens";

export type ApplyPhase49Options = ApplyPhase22Options;
export type ApplyPhase49Result = ApplyPhase22Result;
const OLD_SLUG = "维斯康蒂-visconti-homo-sapiens智人";
function digest(value: string): string { return createHash("sha256").update(value).digest("hex"); }
function stableId(prefix: string, value: string): string { return `${prefix}-${digest(value).slice(0, 24)}`; }
function isInside(candidate: string, root: string): boolean { const relative = path.relative(root, candidate); return relative !== "" && !relative.startsWith("..") && !path.isAbsolute(relative); }
function assertNoRemoteSelection(env: NodeJS.ProcessEnv): void { for (const key of ["TURSO_DATABASE_URL", "TURSO_AUTH_TOKEN", "FPKG_DATABASE_URL"] as const) if (env[key]?.trim()) throw new Error(`Phase 49 refuses inherited remote selection: ${key}.`); }
async function assertOwned(client: Client, options: ApplyPhase49Options): Promise<void> { assertNoRemoteSelection(options.env ?? process.env); assertCatalogSnapshotUnchanged(options.protectedCatalogSnapshot); const ownedRoot = fs.realpathSync.native(options.ownedRoot); const databasePath = fs.realpathSync.native(options.databasePath); const protectedPath = fs.realpathSync.native(options.protectedCatalogPath); if (!fs.statSync(ownedRoot).isDirectory() || !fs.statSync(databasePath).isFile() || fs.lstatSync(options.databasePath).isSymbolicLink() || !isInside(databasePath, ownedRoot)) throw new Error("Phase 49 owned catalog authority check failed."); const own = fs.statSync(databasePath, { bigint: true }); const real = fs.statSync(protectedPath, { bigint: true }); if (databasePath === protectedPath || (own.dev === real.dev && own.ino === real.ino)) throw new Error("Phase 49 refuses protected catalog or hard-link alias."); const listed = await client.execute("PRAGMA database_list"); const main = listed.rows.find((row) => String(row.name) === "main"); if (!main?.file || fs.realpathSync.native(String(main.file)) !== databasePath) throw new Error("Phase 49 client is not bound to owned copy."); const migration = await client.execute({ sql: "SELECT 1 AS ok FROM migrations WHERE name = ? AND checksum IS NOT NULL", args: ["032_taxonomy_identity.sql"] }); if (migration.rows.length !== 1) throw new Error("Phase 49 owned copy must be migrated through 032."); }
async function ensureEntity(tx: Awaited<ReturnType<Client["transaction"]>>, input: { id: string; type: "pen"; slug: string; name: string; brandId: string }): Promise<void> { const rows = await tx.execute({ sql: "SELECT id, type, slug FROM entities WHERE id = ? OR slug = ? ORDER BY id", args: [input.id, input.slug] }); if (rows.rows.length === 0) await tx.execute({ sql: "INSERT INTO entities (id, type, slug, name) VALUES (?, ?, ?, ?)", args: [input.id, input.type, input.slug, input.name] }); else if (rows.rows.length !== 1 || String(rows.rows[0]?.id) !== input.id || String(rows.rows[0]?.type) !== input.type || String(rows.rows[0]?.slug) !== input.slug) throw new Error(`Phase 49 entity/slug collision: ${input.slug}`); await tx.execute({ sql: "DELETE FROM entity_links WHERE source_id = ? AND link_type = 'made_by' AND target_id <> ?", args: [input.id, input.brandId] }); await tx.execute({ sql: "INSERT OR IGNORE INTO entity_links (id, source_id, target_id, link_type, reason) VALUES (?, ?, ?, 'made_by', ?)", args: [stableId("phase49-link", `${input.id}:made_by:${input.brandId}`), input.id, input.brandId, "Phase 49 concrete Visconti Homo Sapiens maker relation"] }); }
async function recordAction(tx: Awaited<ReturnType<Client["transaction"]>>, input: { key: string; sourceId: string; targetId: string }): Promise<{ batchId: string; actionId: string }> { const batchId = stableId("phase49-batch", input.key); const actionId = stableId("phase49-action", input.key); await tx.execute({ sql: "INSERT OR IGNORE INTO taxonomy_batches (id, source_key, source_checksum, status, note) VALUES (?, ?, ?, 'applied', ?)", args: [batchId, input.key, digest(input.key), `Phase 49 retire: ${input.sourceId} -> ${input.targetId}`] }); await tx.execute({ sql: "INSERT OR IGNORE INTO taxonomy_actions (id, batch_id, source_row_key, action_kind, action_checksum, source_entity_id, target_entity_id, status, note) VALUES (?, ?, ?, 'retire', ?, ?, ?, 'applied', ?)", args: [actionId, batchId, input.key, digest(`${input.key}\0${input.sourceId}\0${input.targetId}`), input.sourceId, input.targetId, "Retire generic Homo Sapiens placeholder in favour of concrete siblings and Visconti brand navigation."] }); return { batchId, actionId }; }
async function installRedirect(tx: Awaited<ReturnType<Client["transaction"]>>, input: { sourcePath: string; targetPath: string; actionId: string; batchId: string }): Promise<void> { const existing = await tx.execute({ sql: "SELECT redirect_kind, target_path FROM entity_redirects WHERE source_path = ?", args: [input.sourcePath] }); if (existing.rows.length > 0) { const row = existing.rows[0]; if (String(row?.redirect_kind) !== "permanent" || String(row?.target_path) !== input.targetPath) throw new Error(`Phase 49 conflicting redirect for ${input.sourcePath}.`); return; } await tx.execute({ sql: "INSERT INTO entity_redirects (id, batch_id, action_id, source_path, target_path, redirect_kind, fallback_reason) VALUES (?, ?, ?, ?, ?, 'permanent', ?)", args: [stableId("phase49-redirect", input.sourcePath), input.batchId, input.actionId, input.sourcePath, input.targetPath, "generic_homo_sapiens_retired_for_concrete_siblings"] }); }
async function ensureIdentity(client: Client): Promise<void> { const tx = await client.transaction("write"); try { const brand = await tx.execute({ sql: "SELECT type, slug FROM entities WHERE id = ?", args: [PHASE49_VISCONTI_BRAND_ID] }); if (brand.rows.length !== 1 || String(brand.rows[0]?.type) !== "brand" || String(brand.rows[0]?.slug) !== "visconti") throw new Error("Phase 49 Visconti brand identity missing."); const old = await tx.execute({ sql: "SELECT type, slug FROM entities WHERE id = ?", args: [PHASE49_VISCONTI_OLD_HOMO_ID] }); if (old.rows.length !== 1 || String(old.rows[0]?.type) !== "pen" || String(old.rows[0]?.slug) !== OLD_SLUG) throw new Error("Phase 49 generic Homo Sapiens identity missing."); const action = await recordAction(tx, { key: "phase49-visconti-generic-homo-retire", sourceId: PHASE49_VISCONTI_OLD_HOMO_ID, targetId: PHASE49_VISCONTI_BRAND_ID }); await tx.execute({ sql: "DELETE FROM entity_links WHERE source_id = ?", args: [PHASE49_VISCONTI_OLD_HOMO_ID] }); await tx.execute({ sql: "UPDATE entity_publications SET status = 'retired', blockers_json = ?, approved_content_hash = NULL, reviewed_content_revision = NULL, reviewed_contract_version = NULL, reviewed_by = NULL, reviewed_at = NULL, published_at = NULL, review_notes = ?, updated_at = datetime('now') WHERE entity_id = ? AND status <> 'retired'", args: ['["taxonomy_retired"]', "Generic Homo Sapiens placeholder retired; use concrete Lava Bronze, Dark Age, Lava Color, Crystal Dream, Dark Crystal or Visconti brand.", PHASE49_VISCONTI_OLD_HOMO_ID] }); await installRedirect(tx, { sourcePath: `/pen/${OLD_SLUG}`, targetPath: "/brand/visconti", actionId: action.actionId, batchId: action.batchId }); const pens = [{ id: PHASE49_LAVA_BRONZE_ID, slug: "visconti-homo-sapiens-lava-bronze", name: "维斯康蒂 Visconti Homo Sapiens Lava Bronze" }, { id: PHASE49_LAVA_DARK_AGE_ID, slug: "visconti-homo-sapiens-lava-dark-age", name: "维斯康蒂 Visconti Homo Sapiens Lava Dark Age" }, { id: PHASE49_LAVA_COLOR_ID, slug: "visconti-homo-sapiens-lava-color", name: "维斯康蒂 Visconti Homo Sapiens Lava Color" }, { id: PHASE49_CRYSTAL_DREAM_ID, slug: "visconti-homo-sapiens-crystal-dream", name: "维斯康蒂 Visconti Homo Sapiens Crystal Dream" }, { id: PHASE49_DARK_CRYSTAL_ID, slug: "visconti-homo-sapiens-dark-crystal", name: "维斯康蒂 Visconti Homo Sapiens Dark Crystal" }]; for (const pen of pens) await ensureEntity(tx, { ...pen, type: "pen", brandId: PHASE49_VISCONTI_BRAND_ID }); await tx.commit(); } catch (error) { if (!tx.closed) await tx.rollback(); throw error; } }
export async function applyPhase49ViscontiHomoSapiensContent(client: Client, options: ApplyPhase49Options): Promise<ApplyPhase49Result> { await assertOwned(client, options); await ensureIdentity(client); const result = await applyCuratedContentPacks(client, options, structuredClone(phase49ViscontiHomoSapiensPacks)); assertCatalogSnapshotUnchanged(options.protectedCatalogSnapshot); return result; }
