import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import type { Client } from "@libsql/client";
import { assertCatalogSnapshotUnchanged } from "../src/lib/audit/read-only-catalog";
import { applyCuratedContentPacks, type ApplyPhase22Options, type ApplyPhase22Result } from "./apply-phase22-content";
import { PHASE48_AURORA_88_ID, PHASE48_AURORA_BRAND_ID, PHASE48_AURORA_GENERIC_ID, PHASE48_AURORA_OPTIMA_ID, PHASE48_WATERMAN_BRAND_ID, PHASE48_WATERMAN_CHARLESTON_ID, PHASE48_WATERMAN_HEMISPHERE_ID, phase48WatermanAuroraPacks } from "./data/phase48-waterman-aurora";

export type ApplyPhase48Options = ApplyPhase22Options;
export type ApplyPhase48Result = ApplyPhase22Result;
const OLD_WATERMAN_SLUG = "威迪文-waterman-查尔斯顿-hemisphere";
const OLD_AURORA_SLUG = "奥罗拉-aurora";
function digest(value: string): string { return createHash("sha256").update(value).digest("hex"); }
function stableId(prefix: string, value: string): string { return `${prefix}-${digest(value).slice(0, 24)}`; }
function isInside(candidate: string, root: string): boolean { const relative = path.relative(root, candidate); return relative !== "" && !relative.startsWith("..") && !path.isAbsolute(relative); }
function assertNoRemoteSelection(env: NodeJS.ProcessEnv): void { for (const key of ["TURSO_DATABASE_URL", "TURSO_AUTH_TOKEN", "FPKG_DATABASE_URL"] as const) if (env[key]?.trim()) throw new Error(`Phase 48 refuses inherited remote selection: ${key}.`); }
async function assertOwned(client: Client, options: ApplyPhase48Options): Promise<void> { assertNoRemoteSelection(options.env ?? process.env); assertCatalogSnapshotUnchanged(options.protectedCatalogSnapshot); const ownedRoot = fs.realpathSync.native(options.ownedRoot); const databasePath = fs.realpathSync.native(options.databasePath); const protectedPath = fs.realpathSync.native(options.protectedCatalogPath); if (!fs.statSync(ownedRoot).isDirectory() || !fs.statSync(databasePath).isFile() || fs.lstatSync(options.databasePath).isSymbolicLink() || !isInside(databasePath, ownedRoot)) throw new Error("Phase 48 owned catalog authority check failed."); const own = fs.statSync(databasePath, { bigint: true }); const real = fs.statSync(protectedPath, { bigint: true }); if (databasePath === protectedPath || (own.dev === real.dev && own.ino === real.ino)) throw new Error("Phase 48 refuses protected catalog or hard-link alias."); const listed = await client.execute("PRAGMA database_list"); const main = listed.rows.find((row) => String(row.name) === "main"); if (!main?.file || fs.realpathSync.native(String(main.file)) !== databasePath) throw new Error("Phase 48 client is not bound to owned copy."); const migration = await client.execute({ sql: "SELECT 1 AS ok FROM migrations WHERE name = ? AND checksum IS NOT NULL", args: ["032_taxonomy_identity.sql"] }); if (migration.rows.length !== 1) throw new Error("Phase 48 owned copy must be migrated through 032."); }
async function recordAction(tx: Awaited<ReturnType<Client["transaction"]>>, input: { key: string; sourceId: string; targetId: string; kind: "rename" | "retire" }): Promise<{ batchId: string; actionId: string }> { const batchId = stableId("phase48-batch", input.key); const actionId = stableId("phase48-action", input.key); await tx.execute({ sql: "INSERT OR IGNORE INTO taxonomy_batches (id, source_key, source_checksum, status, note) VALUES (?, ?, ?, 'applied', ?)", args: [batchId, input.key, digest(input.key), `Phase 48 ${input.kind}: ${input.sourceId} -> ${input.targetId}`] }); await tx.execute({ sql: "INSERT OR IGNORE INTO taxonomy_actions (id, batch_id, source_row_key, action_kind, action_checksum, source_entity_id, target_entity_id, status, note) VALUES (?, ?, ?, ?, ?, ?, ?, 'applied', ?)", args: [actionId, batchId, input.key, input.kind, digest(`${input.key}\0${input.sourceId}\0${input.targetId}`), input.sourceId, input.targetId, `Phase 48 ${input.kind} identity action.`] }); if (input.kind === "rename") await tx.execute({ sql: "INSERT OR IGNORE INTO entity_lineage (id, batch_id, action_id, source_entity_id, target_entity_id, lineage_kind, fallback_reason) VALUES (?, ?, ?, ?, ?, 'rename', NULL)", args: [stableId("phase48-lineage", input.key), batchId, actionId, input.sourceId, input.targetId] }); return { batchId, actionId }; }
async function installRedirect(tx: Awaited<ReturnType<Client["transaction"]>>, input: { sourcePath: string; targetPath?: string; kind: "permanent" | "hard_404"; actionId: string; batchId: string }): Promise<void> { const existing = await tx.execute({ sql: "SELECT redirect_kind, target_path FROM entity_redirects WHERE source_path = ?", args: [input.sourcePath] }); if (existing.rows.length > 0) { const row = existing.rows[0]; if (String(row?.redirect_kind) !== input.kind || (input.targetPath ?? null) !== (row?.target_path == null ? null : String(row.target_path))) throw new Error(`Phase 48 conflicting redirect for ${input.sourcePath}.`); return; } await tx.execute({ sql: "INSERT INTO entity_redirects (id, batch_id, action_id, source_path, target_path, redirect_kind, fallback_reason) VALUES (?, ?, ?, ?, ?, ?, ?)", args: [stableId("phase48-redirect", input.sourcePath), input.batchId, input.actionId, input.sourcePath, input.targetPath ?? null, input.kind, input.kind === "hard_404" ? "brand_generic_placeholder_retired" : "canonical_identity_rename"] }); }
async function ensureEntity(tx: Awaited<ReturnType<Client["transaction"]>>, input: { id: string; slug: string; name: string; brandId: string }): Promise<void> { const existing = await tx.execute({ sql: "SELECT id, type, slug FROM entities WHERE id = ? OR slug = ? ORDER BY id", args: [input.id, input.slug] }); if (existing.rows.length === 0) await tx.execute({ sql: "INSERT INTO entities (id, type, slug, name) VALUES (?, 'pen', ?, ?)", args: [input.id, input.slug, input.name] }); else if (existing.rows.length !== 1 || String(existing.rows[0]?.id) !== input.id || String(existing.rows[0]?.type) !== "pen" || String(existing.rows[0]?.slug) !== input.slug) throw new Error(`Phase 48 entity/slug collision: ${input.slug}`); await tx.execute({ sql: "DELETE FROM entity_links WHERE source_id = ? AND link_type = 'made_by' AND target_id <> ?", args: [input.id, input.brandId] }); await tx.execute({ sql: "INSERT OR IGNORE INTO entity_links (id, source_id, target_id, link_type, reason) VALUES (?, ?, ?, 'made_by', ?)", args: [stableId("phase48-link", `${input.id}:made_by:${input.brandId}`), input.id, input.brandId, "Phase 48 concrete maker relation"] }); }
async function ensureIdentity(client: Client): Promise<void> { const tx = await client.transaction("write"); try { const brands = await tx.execute({ sql: "SELECT id, type FROM entities WHERE id IN (?, ?)", args: [PHASE48_WATERMAN_BRAND_ID, PHASE48_AURORA_BRAND_ID] }); if (brands.rows.length !== 2 || brands.rows.some((row) => String(row?.type) !== "brand")) throw new Error("Phase 48 Waterman/Aurora brand identity missing."); const waterman = await tx.execute({ sql: "SELECT type, slug FROM entities WHERE id = ?", args: [PHASE48_WATERMAN_HEMISPHERE_ID] }); if (waterman.rows.length !== 1 || String(waterman.rows[0]?.type) !== "pen") throw new Error("Phase 48 Waterman Hémisphère identity missing."); if (String(waterman.rows[0]?.slug) !== "waterman-hemisphere") { const action = await recordAction(tx, { key: "phase48-waterman-hemisphere-rename", sourceId: PHASE48_WATERMAN_HEMISPHERE_ID, targetId: PHASE48_WATERMAN_HEMISPHERE_ID, kind: "rename" }); await tx.execute({ sql: "UPDATE entities SET slug = ?, name = ?, updated_at = datetime('now') WHERE id = ?", args: ["waterman-hemisphere", "威迪文 Waterman Hémisphère", PHASE48_WATERMAN_HEMISPHERE_ID] }); await installRedirect(tx, { sourcePath: `/pen/${OLD_WATERMAN_SLUG}`, targetPath: "/pen/waterman-hemisphere", kind: "permanent", actionId: action.actionId, batchId: action.batchId }); } else { const action = await recordAction(tx, { key: "phase48-waterman-hemisphere-rename", sourceId: PHASE48_WATERMAN_HEMISPHERE_ID, targetId: PHASE48_WATERMAN_HEMISPHERE_ID, kind: "rename" }); await installRedirect(tx, { sourcePath: `/pen/${OLD_WATERMAN_SLUG}`, targetPath: "/pen/waterman-hemisphere", kind: "permanent", actionId: action.actionId, batchId: action.batchId }); }
    const generic = await tx.execute({ sql: "SELECT type FROM entities WHERE id = ?", args: [PHASE48_AURORA_GENERIC_ID] }); if (generic.rows.length !== 1 || String(generic.rows[0]?.type) !== "pen") throw new Error("Phase 48 Aurora generic placeholder missing."); const retire = await recordAction(tx, { key: "phase48-aurora-generic-retire", sourceId: PHASE48_AURORA_GENERIC_ID, targetId: PHASE48_AURORA_BRAND_ID, kind: "retire" }); await tx.execute({ sql: "DELETE FROM entity_links WHERE source_id = ?", args: [PHASE48_AURORA_GENERIC_ID] }); await tx.execute({ sql: "UPDATE entity_publications SET status = 'retired', blockers_json = ?, approved_content_hash = NULL, reviewed_content_revision = NULL, reviewed_contract_version = NULL, reviewed_by = NULL, reviewed_at = NULL, published_at = NULL, review_notes = ?, updated_at = datetime('now') WHERE entity_id = ? AND status <> 'retired'", args: ['["entity_type_placeholder"]', "Aurora generic placeholder retired; use concrete Aurora 88 or Optima.", PHASE48_AURORA_GENERIC_ID] }); await installRedirect(tx, { sourcePath: `/pen/${OLD_AURORA_SLUG}`, kind: "hard_404", actionId: retire.actionId, batchId: retire.batchId });
    await ensureEntity(tx, { id: PHASE48_WATERMAN_CHARLESTON_ID, slug: "waterman-charleston", name: "威迪文 Waterman Charleston", brandId: PHASE48_WATERMAN_BRAND_ID }); await ensureEntity(tx, { id: PHASE48_AURORA_88_ID, slug: "aurora-88", name: "奥罗拉 Aurora 88", brandId: PHASE48_AURORA_BRAND_ID }); await ensureEntity(tx, { id: PHASE48_AURORA_OPTIMA_ID, slug: "aurora-optima", name: "奥罗拉 Aurora Optima", brandId: PHASE48_AURORA_BRAND_ID }); await tx.commit(); } catch (error) { if (!tx.closed) await tx.rollback(); throw error; } }
export async function applyPhase48WatermanAuroraContent(client: Client, options: ApplyPhase48Options): Promise<ApplyPhase48Result> { await assertOwned(client, options); await ensureIdentity(client); const packs = structuredClone(phase48WatermanAuroraPacks); const watermanIds = new Set([PHASE48_WATERMAN_BRAND_ID, PHASE48_WATERMAN_HEMISPHERE_ID, PHASE48_WATERMAN_CHARLESTON_ID]); const auroraIds = new Set([PHASE48_AURORA_BRAND_ID, PHASE48_AURORA_88_ID, PHASE48_AURORA_OPTIMA_ID]); const entities: ApplyPhase48Result["entities"] = []; for (const batch of [packs.filter((pack) => watermanIds.has(pack.entityId)), packs.filter((pack) => auroraIds.has(pack.entityId))]) { const result = await applyCuratedContentPacks(client, options, batch); entities.push(...result.entities); } assertCatalogSnapshotUnchanged(options.protectedCatalogSnapshot); return { entities }; }
