import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import type { Client } from "@libsql/client";
import { assertCatalogSnapshotUnchanged, snapshotCatalogFiles } from "../src/lib/audit/read-only-catalog";
import { applyCuratedContentPacks, type ApplyPhase22Options, type ApplyPhase22Result } from "./apply-phase22-content";
import { PHASE99_CONKLIN_BRAND_ID, PHASE99_GLIDER_ID, PHASE99_NOZAC_ID, phase99ConklinHistoricPacks } from "./data/phase99-conklin-historic";
export type ApplyPhase99Options = ApplyPhase22Options;
export type ApplyPhase99Result = ApplyPhase22Result;
const id = (prefix: string, value: string) => `${prefix}-${createHash("sha256").update(value).digest("hex").slice(0, 24)}`;
const inside = (candidate: string, root: string) => { const relative = path.relative(root, candidate); return relative !== "" && !relative.startsWith("..") && !path.isAbsolute(relative); };
async function owned(client: Client, options: ApplyPhase99Options) { for (const key of ["TURSO_DATABASE_URL", "TURSO_AUTH_TOKEN", "FPKG_DATABASE_URL"] as const) if ((options.env ?? process.env)[key]?.trim()) throw new Error(`Phase 99 refuses inherited remote selection: ${key}.`); assertCatalogSnapshotUnchanged(options.protectedCatalogSnapshot); const root = fs.realpathSync.native(options.ownedRoot), database = fs.realpathSync.native(options.databasePath), protectedCatalog = fs.realpathSync.native(options.protectedCatalogPath); if (!fs.statSync(root).isDirectory() || !fs.statSync(database).isFile() || fs.lstatSync(options.databasePath).isSymbolicLink() || !inside(database, root)) throw new Error("Phase 99 database must be a non-symlink file inside the owned root."); const own = fs.statSync(database, { bigint: true }), real = fs.statSync(protectedCatalog, { bigint: true }); if (database === protectedCatalog || (own.dev === real.dev && own.ino === real.ino)) throw new Error("Phase 99 refuses protected catalog or hard-link alias."); const main = (await client.execute("PRAGMA database_list")).rows.find((row) => String(row.name) === "main"); if (!main?.file || fs.realpathSync.native(String(main.file)) !== database) throw new Error("Phase 99 client is not bound to the authorized owned copy."); const migration = await client.execute({ sql: "SELECT 1 FROM migrations WHERE name=? AND checksum IS NOT NULL", args: ["032_taxonomy_identity.sql"] }); if (migration.rows.length !== 1) throw new Error("Phase 99 owned copy must be migrated through 032."); }
async function topology(client: Client) { const transaction = await client.transaction("write"); try { const rows = await transaction.execute({ sql: "SELECT id,type,slug FROM entities WHERE id IN (?,?,?) ORDER BY id", args: [PHASE99_CONKLIN_BRAND_ID, PHASE99_NOZAC_ID, PHASE99_GLIDER_ID] }); const expected = new Map([[PHASE99_CONKLIN_BRAND_ID, ["brand", "conklin"]], [PHASE99_NOZAC_ID, ["pen", "the-conklin-nozac"]], [PHASE99_GLIDER_ID, ["pen", "the-conklin-glider"]]]); if (rows.rows.length !== 3 || rows.rows.some((row) => { const item = expected.get(String(row.id)); return !item || String(row.type) !== item[0] || String(row.slug) !== item[1]; })) throw new Error("Phase 99 Conklin identity mismatch."); for (const penId of [PHASE99_NOZAC_ID, PHASE99_GLIDER_ID]) { await transaction.execute({ sql: "DELETE FROM entity_links WHERE source_id=? AND link_type='made_by' AND target_id<>?", args: [penId, PHASE99_CONKLIN_BRAND_ID] }); await transaction.execute({ sql: "INSERT OR IGNORE INTO entity_links (id,source_id,target_id,link_type,reason) VALUES (?,?,?,'made_by',?)", args: [id("phase99-made-by", penId), penId, PHASE99_CONKLIN_BRAND_ID, "Phase 99 verified Conklin maker relation"] }); await transaction.execute({ sql: "INSERT OR IGNORE INTO entity_links (id,source_id,target_id,link_type,reason) VALUES (?,?,?,'reverse',?)", args: [id("phase99-reverse", penId), PHASE99_CONKLIN_BRAND_ID, penId, "Phase 99 Conklin brand navigation"] }); } await transaction.commit(); } catch (error) { if (!transaction.closed) await transaction.rollback(); throw error; } }
export async function applyPhase99ConklinHistoricContent(client: Client, options: ApplyPhase99Options): Promise<ApplyPhase99Result> { await owned(client, options); await topology(client); const result = await applyCuratedContentPacks(client, options, structuredClone(phase99ConklinHistoricPacks)); assertCatalogSnapshotUnchanged(options.protectedCatalogSnapshot); return result; }
const value = (name: string) => { const index = process.argv.indexOf(name); return index === -1 ? null : process.argv[index + 1] ?? null; };
async function main() { const databasePath = value("--database"), ownedRoot = value("--owned-root"), protectedCatalogPath = value("--protected-catalog"); if (!databasePath || !ownedRoot || !protectedCatalogPath) throw new Error("Usage: tsx scripts/apply-phase99-conklin-historic-content.ts --database <owned-copy> --owned-root <root> --protected-catalog <real-db>"); const { createClient } = await import("@libsql/client"); const client = createClient({ url: `file:${path.resolve(databasePath)}` }); try { process.stdout.write(`${JSON.stringify(await applyPhase99ConklinHistoricContent(client, { workspaceRoot: process.cwd(), reviewer: value("--reviewer") ?? "phase99-conklin", databasePath: path.resolve(databasePath), ownedRoot: path.resolve(ownedRoot), protectedCatalogPath: path.resolve(protectedCatalogPath), protectedCatalogSnapshot: snapshotCatalogFiles(path.resolve(protectedCatalogPath)), env: { ...process.env, TURSO_DATABASE_URL: "", TURSO_AUTH_TOKEN: "", FPKG_DATABASE_URL: "" } }), null, 2)}\n`); } finally { client.close(); } }
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) void main().catch((error) => { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
