import fs from "node:fs";
import path from "node:path";
import Database from "better-sqlite3";
import {
  ARTICLE_SUMMARY_LIMITS,
  articleSummaryFromMarkdown,
  isCleanArticleSummary,
} from "../src/lib/article-summary";

const DATABASE_PATH = path.join(process.cwd(), "data", "fpkg.db");
const OUTPUT_PATH = path.join(
  process.cwd(),
  "migrations",
  "018_article_summaries.sql",
);

type ArticleRow = {
  id: string;
  slug: string;
  summary: string | null;
  body_md: string | null;
};

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const db = new Database(DATABASE_PATH, { readonly: true, fileMustExist: true });
const articles = db
  .prepare(
    `SELECT id, slug, summary, body_md
     FROM entities
     WHERE type = 'article'
     ORDER BY slug`,
  )
  .all() as ArticleRow[];
db.close();

if (articles.length !== 208) {
  throw new Error(`Expected 208 articles, found ${articles.length}.`);
}

const updates = articles.map((article) => {
  // The existing summary is appended only as a last-resort factual source for
  // exceptionally short placeholder bodies; full articles reach the target
  // length from body_md before this fallback is considered.
  const source = [article.body_md, article.summary].filter(Boolean).join("\n\n");
  const summary = articleSummaryFromMarkdown(source);
  if (!isCleanArticleSummary(summary)) {
    throw new Error(
      `Invalid summary for ${article.slug}: length=${summary.length}, value=${JSON.stringify(summary)}`,
    );
  }

  return `UPDATE entities SET summary = ${sqlString(summary)}, updated_at = datetime('now') WHERE id = ${sqlString(article.id)} AND type = 'article';`;
});

const migration = [
  "-- Deterministic summaries extracted from each article's first useful factual prose.",
  `-- Generated by scripts/generate-article-summary-migration.ts (${articles.length} articles, ${ARTICLE_SUMMARY_LIMITS.min}-${ARTICLE_SUMMARY_LIMITS.max} characters).`,
  "BEGIN;",
  ...updates,
  "COMMIT;",
  "",
].join("\n");

if (process.argv.includes("--write")) {
  fs.writeFileSync(OUTPUT_PATH, migration, "utf8");
  console.log(`Wrote ${updates.length} summaries to ${OUTPUT_PATH}`);
} else {
  process.stdout.write(migration);
}
